[package]
name = "ble-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.10.0"
futures = "0.3.24"
tokio = {version = "1.20.1", features = ["full"]}
uuid = "1.1.2"
